spring:
  application:
    name: weather-monitor

  datasource:
    url: jdbc:h2:file:./data/weatherdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  thymeleaf:
    cache: false

  jackson:
    serialization:
      indent_output: true
      write-dates-as-timestamps: false

  cache:
    type: caffeine
    cache-names: latest, history
    caffeine:
      spec: maximumSize=2000,expireAfterWrite=60s

server:
  port: 8080

openweather:
  base-url: https://api.openweathermap.org/data/2.5
  api-key: ${OPENWEATHER_API_KEY}
  units: metric
  language: pl

weather:
  scheduler:
    enabled: true
    refresh-interval-ms: 600000

  measurements:
    history-limit: 50

logging:
  file:
    name: logs/weather-monitor.log
  level:
    root: INFO
    pl.edu.pjatk.weathermonitor: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: OFF
    org.hibernate.type.descriptor.sql: OFF
